#声明电影购票微服务的端口号
server:
  port: 8001

spring:
  application:
    name: microservice-movie
#网关向zipkin服务器发送信息
  zipkin:
    base-url: http://192.168.222.1:9041
    sender:
      type: web  #给zipkin发送信息的sender类型是web服务器而不是RabbitMQ.
  #100%跟踪采样
  sleuth:
    sampler:
      probability: 1
#eureka客户端向eureka服务器注册
eureka:
  client:
    #向Eure服务器注册
    register-with-eureka: true
    #向eureka服务器索要信息
    fetch-registry: true
    #注册服务的url
    service-url:
      defaultZone: http://192.168.222.1:8888/eureka

    #微服务的消费方与eureka服务器的约定
    #每30秒从eureka服务器获得最新的信息
    registry-fetch-interval-seconds: 30 #默认30秒
